# Configuration file to store build system requirements for Python projects
# https://www.python.org/dev/peps/pep-0518/

[tool.isort]
# make the tools compatible to each other
profile = "black"

[tool.pytest.ini_options]
log_level = "INFO"
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "serial",
]
