name: Publish SQLite Cloud to PyPI

on:
    workflow_dispatch:

jobs:
  release:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: Bump version and tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
      - name: Set version
        run: |
              git config --local user.email "github-actions[bot]@users.noreply.github.com"
              git config --local user.name "github-actions[bot]"
              python -m pip install -r requirements-dev.txt
              bump2version patch
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force: true
          tags: true

  build-n-publish:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: Build and publish SQLite Cloud to PyPI
    needs: release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install pypa/setuptools
      run: >-
        python -m
        pip install wheel
    - name: Extract tag name
      id: tag
      run: echo ::set-output name=TAG_NAME::$(echo $GITHUB_REF | cut -d / -f 3)
    - name: Update version in setup.py
      run: >-
        sed -i "s/{{VERSION_PLACEHOLDER}}/${{ steps.tag.outputs.TAG_NAME }}/g" src/setup.py
    - name: Include README in package
      run: >-
        cp README.md src/README.md
    - name: Build a binary wheel
      run: |
        cd src
        python3 -m pip install --upgrade build && python3 -m build
    - name: delete sqlitecloud.egg-info
      run: |
        echo "Current Directory: $(pwd)"
        rm -r src/sqlitecloud.egg-info
        ls src/
    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: src/dist/
        password: ${{ secrets.PYPI_API_TOKEN }}
